language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: PHPUNIT=^7.0
    - php: 7.2
      env: PHPUNIT=^7.0
    - php: 7.2
      env: PHPUNIT=^8.0
    - php: 7.3
      env: PHPUNIT=^7.0
    - php: 7.3
      env: PHPUNIT=^8.0

sudo: false

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - travis_retry composer require phpunit/phpunit:$PHPUNIT --update-with-dependencies

before_script: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

script: vendor/bin/phpunit --verbose
