language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - LARAVEL=5.7.* PHPUNIT=^7.5
    - LARAVEL=5.7.* PHPUNIT=^8.0
    - LARAVEL=5.8.* PHPUNIT=^7.5
    - LARAVEL=5.8.* PHPUNIT=^8.0
    - LARAVEL=^6.0 PHPUNIT=^7.5
    - LARAVEL=^6.0 PHPUNIT=^8.0
    - LARAVEL=^7.0 PHPUNIT=^8.0

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: LARAVEL=5.7.* PHPUNIT=^8.0
    - php: 7.1
      env: LARAVEL=5.8.* PHPUNIT=^8.0
    - php: 7.1
      env: LARAVEL=^6.0 PHPUNIT=^7.5
    - php: 7.1
      env: LARAVEL=^6.0 PHPUNIT=^8.0
    - php: 7.1
      env: LARAVEL=^7.0 PHPUNIT=^8.0
  allow_failures:
    - env: LARAVEL=^7.0 PHPUNIT=^8.0

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer require "illuminate/contracts=${LARAVEL}" "phpunit/phpunit:${PHPUNIT}" --dev --prefer-dist --no-interaction --no-suggest

before_script:
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

script: vendor/bin/phpunit --verbose
